storage:
  classname: ${STORAGE_CLASSNAME}
  parameters:
    retain_input_files: ${RETAIN_INPUT_FILES}
    root_dir: ${ROOT_DIR}
    bucket_name: ${STORAGE_BUCKET}

  file_handlers:
    input:
      ecor:
        file_pattern: '.*sgpecorE14\.\d{2}\.\d{8}\.\d{6}\.raw\..*\.flx'
        classname: ingest.ecor.pipeline.filehandler.EcorFileHandler

    output:
      netcdf:
        file_extension: ".nc"
        classname: tsdat.io.filehandlers.NetCdfHandler
