# https://github.com/tsdat/tsdat/blob/main/examples/templates/ingest_pipeline_template.yml
# or open an existing example in this repository to see what you can do here. Note that
# the A2e program uses slightly different metadata conventions than tsdat and a
# reviewer can help you determine which metadata should be included here.

pipeline:
  type: Ingest

  # These parameters will be used to name files.
  location_id: "nwtc"
  dataset_name: "flux_sonics_nwtc"
  # qualifier: ""
  # temporal: ""
  data_level: "a0" # If not applying QC this should be set to "a0"

dataset_definition:
  attributes:
    title: "flux_sonics"
    description: "Surface flux station with sonic anemometers"
    conventions: MHKiT-Cloud Data Standards v. 1.0
    institution: Atmosphere to Electrons
    code_url: https://github.com/a2edap/ingest-awaken
    location_meaning: "nwtc"

  dimensions:
    time:
      length: unlimited
    height:
      length: 2

  variables:
    time:
      input:
        name: TIMESTAMP
        converter:
          classname: tsdat.utils.converters.StringTimeConverter
          parameters:
            timezone: UTC
            time_format: "%Y-%m-%d %H:%M:%S"
      dims: [time]
      type: long
      attrs:
        long_name: Time (UTC)
        standard_name: time
        units: seconds since 1970-01-01T00:00:00

    height:
      data: [3, 7]
      dims: [height]
      input:
        name: height
      type: int
      attrs:
        long_name: Height ASL
        units: m

    U_ax:
      dims: [time, height]
      type: float
      input:
        name: U_ax
      attrs:
        long_name: Wind speed, U direction
        standard_name: eastward_wind
        units: m/s

    V_ax:
      dims: [time, height]
      type: float
      input:
        name: V_ax
      attrs:
        long_name: Wind speed, V direction
        standard_name: northward_wind
        units: m/s

    W_ax:
      dims: [time, height]
      type: float
      input:
        name: W_ax
      attrs:
        long_name: Wind speed, vertical
        standard_name: upward_air_velocity
        units: m/s

    eastward_wind:
      dims: [time, height]
      type: float
      # input:
      #   name: U_ax
      attrs:
        long_name: Wind speed, eastward
        description: Eastward indicates a vector component which is positive when directed eastward (negative westward). Wind is defined as a two-dimensional (horizontal) air velocity vector, with no vertical component. (Vertical motion in the atmosphere has the standard name upward_air_velocity.)
        standard_name: eastward_wind
        units: m/s

    # northward_wind:
    #   dims: [time, height]
    #   type: float
    #   input:
    #     name: V_ax
    #   attrs:
    #     long_name: Wind speed, northward
    #     description: Northward indicates a vector component which is positive when directed northward (negative westward). Wind is defined as a two-dimensional (horizontal) air velocity vector, with no vertical component. (Vertical motion in the atmosphere has the standard name upward_air_velocity.)
    #     standard_name: northward_wind
    #     units: m/s

    # upward_air_velocity:
    #   dims: [time, height]
    #   type: float
    #   input:
    #     name: W_ax
    #   attrs:
    #     long_name: Wind speed, vertical
    #     description: A velocity is a vector quantity. "Upward" indicates a vector component which is positive when directed upward (negative downward). Upward air velocity is the vertical component of the 3D air velocity vector. The standard name downward_air_velocity may be used for a vector component with the opposite sign convention.
    #     standard_name: upward_air_velocity
    #     units: m/s

    # wind_speed:
    #   dims: [time, height]
    #   type: float
    #   attrs:
    #     long_name: Wind speed
    #     description: Speed is the magnitude of velocity. Wind is defined as a two-dimensional (horizontal) air velocity vector, with no vertical component. (Vertical motion in the atmosphere has the standard name upward_air_velocity.) The wind speed is the magnitude of the wind velocity.
    #     standard_name: wind_speed
    #     units: m/s

    # wind_direction:
    #   dims: [time, height]
    #   type: float
    #   attrs:
    #     long_name: Wind direction
    #     standard_name: wind_direction
    #     units: m/s

    Ts:
      dims: [time, height]
      type: float
      input:
        name: Ts
      attrs:
        long_name: Temperature, sonic
        description: The air temperature as calculated with sonic (acoustic) thermometry.
        standard_name: air_temperature
        units: degC

    # air_temperature:
    #   dims: [time, height]
    #   type: float
    #   input:
    #     name: Ts
    #   attrs:
    #     long_name: Temperature, sonic
    #     description: The air temperature as calculated with sonic (acoustic) thermometry.
    #     standard_name: air_temperature
    #     units: degC

    latitude:
      data: 71.323
      type: float
      attrs:
        long_name: "North latitude"
        standard_name: "latitude"
        comment: "Recorded lattitude at the instrument location"
        units: "degree_N"
        valid_range: [-90.f, 90.f]

    longitude:
      data: -156.609
      type: float
      attrs:
        long_name: "East longitude"
        standard_name: "longitude"
        comment: "Recorded longitude at the instrument location"
        units: "degree_E"
        valid_range: [-180.f, 180.f]

    altitude:
      data: 4000.0
      type: float
      attrs:
        long_name: "Altitude"
        standard_name: "altitude"
        comment: "Recorded altitude at the instrument location"
        units: m

    orientation:
      data: 270.0
      type: float
      attrs:
        long_name: "Orientation"
        standard_name: "orientation"
        comment: "Orientation of instrument"
        units: degrees

#-----------------------------------------------------------------
quality_management:
  #---------------------------------------------------------------
  manage_missing_coordinates:
    checker:
      classname: tsdat.qc.checkers.CheckMissing
    handlers:
      - classname: tsdat.qc.handlers.FailPipeline
    variables:
      - COORDS

  manage_coordinate_monotonicity:
    checker:
      classname: tsdat.qc.checkers.CheckMonotonic
    handlers:
      - classname: tsdat.qc.handlers.SortDatasetByCoordinate
        parameters:
          ascending: True
          correction: "Coordinate data was sorted in order to ensure monotonicity."
    variables:
      - COORDS

  #---------------------------------------------------------------
  manage_missing_values:
    checker:
      classname: tsdat.qc.checkers.CheckMissing
    handlers:
      - classname: tsdat.qc.handlers.RemoveFailedValues
      - classname: tsdat.qc.handlers.RecordQualityResults
        parameters:
          bit: 1
          assessment: Bad
          meaning: "Value is equal to _FillValue or NaN"
    variables:
      - DATA_VARS
    exclude: [latitude, longitude, altitude]

  manage_custom_qc: # Rename this
    checker:
      classname: ingest.flux_sonics_nwtc.pipeline.qc.CustomQualityChecker
    handlers:
      - classname: ingest.flux_sonics_nwtc.pipeline.qc.CustomQualityHandler
