pipeline:
  type: Ingest

  # These parameters will be used to name files.
  location_id: "nwtc"
  dataset_name: "flux_lowspeed_nwtc"
  # qualifier: ""
  # temporal: ""
  data_level: "a0" # If not applying QC this should be set to "a0"

dataset_definition:
  attributes:
    title: "flux_lowspeed_nwtc"
    description: "Low speed data from surface flux station from NWTC"
    conventions: MHKiT-Cloud Data Standards v. 1.0
    institution: Atmosphere to Electrons
    code_url: https://github.com/a2edap/ingest-awaken
    location_meaning: "nwtc"

  dimensions:
    time:
      length: unlimited

  variables:
    time:
      input:
        name: TIMESTAMP
        converter:
          classname: tsdat.utils.converters.StringTimeConverter
          parameters:
            timezone: UTC
            time_format: "%Y-%m-%d %H:%M:%S"
      dims: [time]
      type: long
      attrs:
        long_name: Time (UTC)
        standard_name: time
        units: seconds since 1970-01-01T00:00:00

    wind_speed:
      dims: [time]
      type: float
      input:
        name: WS_15m
      attrs:
        long_name: Wind speed
        description: Speed is the magnitude of velocity. Wind is defined as a two-dimensional (horizontal) air velocity vector, with no vertical component. (Vertical motion in the atmosphere has the standard name upward_air_velocity.) The wind speed is the magnitude of the wind velocity.
        standard_name: wind_speed
        units: m/s

    surface_air_pressure:
      dims: [time]
      type: float
      input:
        name: Pressure
      attrs:
        long_name: Air pressure, surface
        description: Air pressure is the force per unit area which would be exerted when the moving gas molecules of which the air is composed strike a theoretical surface of any orientation.
        standard_name: surface_air_pressure
        units: hPa

    air_temperature:
      dims: [time]
      type: float
      input:
        name: Temperature
      attrs:
        long_name: Temperature, sonic
        description: Air temperature is the bulk temperature of the air, not the surface (skin) temperature.
        standard_name: air_temperature
        units: degC

    relative_humidity:
      dims: [time]
      type: float
      input:
        name: RelativeHumidity
      attrs:
        long_name: Relative humidity
        description: The ratio of the vapor pressure to the saturation vapor pressure with respect to water.
        standard_name: relative_humidity
        units: "%"

    latitude:
      data: 71.323
      type: float
      attrs:
        long_name: "North latitude"
        standard_name: "latitude"
        comment: "Recorded lattitude at the instrument location"
        units: "degree_N"
        valid_range: [-90.f, 90.f]

    longitude:
      data: -156.609
      type: float
      attrs:
        long_name: "East longitude"
        standard_name: "longitude"
        comment: "Recorded longitude at the instrument location"
        units: "degree_E"
        valid_range: [-180.f, 180.f]

    altitude:
      data: 4000.0
      type: float
      attrs:
        long_name: "Altitude"
        standard_name: "altitude"
        comment: "Recorded altitude at the instrument location"
        units: m

#-----------------------------------------------------------------
quality_management:
  #---------------------------------------------------------------
  manage_missing_coordinates:
    checker:
      classname: tsdat.qc.checkers.CheckMissing
    handlers:
      - classname: tsdat.qc.handlers.FailPipeline
    variables:
      - COORDS

  manage_coordinate_monotonicity:
    checker:
      classname: tsdat.qc.checkers.CheckMonotonic
    handlers:
      - classname: tsdat.qc.handlers.SortDatasetByCoordinate
        parameters:
          ascending: True
          correction: "Coordinate data was sorted in order to ensure monotonicity."
    variables:
      - COORDS

  #---------------------------------------------------------------
  manage_missing_values:
    checker:
      classname: tsdat.qc.checkers.CheckMissing
    handlers:
      - classname: tsdat.qc.handlers.RemoveFailedValues
      - classname: tsdat.qc.handlers.RecordQualityResults
        parameters:
          bit: 1
          assessment: Bad
          meaning: "Value is equal to _FillValue or NaN"
    variables:
      - DATA_VARS
    exclude: [latitude, longitude, altitude]
