pipeline:
  type: Ingest

  # These parameters will be used to name files.
  location_id: "nwtc"
  dataset_name: "wind_cube_profile_rtd"
  # qualifier: ""
  # temporal: ""
  data_level: "b0" # If not applying QC this should be set to "a0"

dataset_definition:
  attributes:
    title: "wind_cube"
    description: "Wind cube v2 ingest"
    conventions: MHKiT-Cloud Data Standards v. 1.0
    institution: Atmosphere to Electrons
    code_url: https://github.com/a2edap/ingest-awaken
    location_meaning: "nwtc"

  dimensions:
    time:
      length: unlimited
    height:
      length: 9

  variables:
    time:
      input:
        name: Timestamp
        converter:
          classname: tsdat.utils.converters.StringTimeConverter
          parameters:
            timezone: UTC
            time_format: "%Y/%m/%d %H:%M"
      dims: [time]
      type: long
      attrs:
        long_name: Time (UTC)
        standard_name: time
        units: seconds since 1970-01-01T00:00:00

    height:
      # data: [41, 55, 61, 74, 80, 87, 92, 100, 105, 119, 122, 130]
      dims: [height]
      type: float
      input:
        name: height
      attrs:
        long_name: height ASL
        units: m

    int_temp:
      dims: [time]
      type: float
      input:
        name: Int Temp (degC)
      attrs:
        long_name: Int Temp
        units: degC

    ext_temp:
      dims: [time]
      type: float
      input:
        name: Ext Temp (degC)
      attrs:
        long_name: Ext Temp
        units: C

    pressure:
      dims: [time]
      type: float
      input:
        name: Pressure (hPa)
      attrs:
        long_name: Pressure
        units: hPa

    rel_humidity:
      dims: [time]
      type: float
      input:
        name: Rel Humidity (%)
      attrs:
        long_name: Rel Humidity
        units: "%"

    wiper_count:
      dims: [time]
      type: int
      input:
        name: wiper_count
      attrs:
        long_name: Wiper Count
        units: count

    Vbatt:
      dims: [time]
      type: float
      input:
        name: Vbatt (V)
      attrs:
        long_name: Vbatt
        units: V

    wind_speed:
      dims: [time, height]
      type: float
      input:
        name: wind_speed
      attrs:
        long_name: Wind Speed
        units: m/s

    wind_speed_rad:
      dims: [time, height]
      type: float
      input:
        name: wind_speed_rad
      attrs:
        long_name: Radial Wind Speed
        units: m/s

    wind_speed_disp:
      dims: [time, height]
      type: float
      input:
        name: wind_speed_disp
      attrs:
        long_name: Radial Wind Speed Dispersion
        units: m/s

    # wind_speed_min:
    #   dims: [time, height]
    #   type: float
    #   attrs:
    #     long_name: Wind Speed Min
    #     units: m/s

    # wind_speed_max:
    #   dims: [time, height]
    #   type: float
    #   attrs:
    #     long_name: Wind Speed Max
    #     units: m/s

    wind_speed_z:
      dims: [time, height]
      type: float
      input:
        name: wind_speed_z
      attrs:
        long_name: z-wind
        units: m/s

    wind_speed_x:
      dims: [time, height]
      type: float
      input:
        name: wind_speed_x
      attrs:
        long_name: x-wind
        units: m/s

    wind_speed_y:
      dims: [time, height]
      type: float
      input:
        name: wind_speed_y
      attrs:
        long_name: y-wind
        units: m/s

    # z_wind_dispersion:
    #   dims: [time, height]
    #   type: float
    #   attrs:
    #     long_name: Z-wind Dispersion
    #     units: m/s

    wind_direction:
      dims: [time, height]
      type: float
      input:
        name: wind_direction
      attrs:
        long_name: Wind Direction
        units: degrees

    cnr:
      dims: [time, height]
      type: float
      input:
        name: cnr
      attrs:
        long_name: Carrier-to-noise ratio
        units: dB

    # crn_min:
    #   dims: [time, height]
    #   type: float
    #   attrs:
    #     long_name: CRN_Min
    #     units: dB

    # dopp_spect_broad:
    #   dims: [time, height]
    #   type: float
    #   attrs:
    #     long_name: Dopp Spect Broad
    #     units: m/s

    # data_availability:
    #   dims: [time, height]
    #   type: float
    #   attrs:
    #     long_name: Availability
    #     units: "%"

    position:
      dims: [time]
      type: int
      input:
        name: Position
      attrs:
        description: Azimuthal position of scan. V is replaced with -1 for a vertical scan.

    latitude:
      data: 71.323
      type: float
      attrs:
        long_name: "North latitude"
        standard_name: "latitude"
        comment: "Recorded lattitude at the instrument location"
        units: "degree_N"
        valid_range: [-90.f, 90.f]

    longitude:
      data: -156.609
      type: float
      attrs:
        long_name: "East longitude"
        standard_name: "longitude"
        comment: "Recorded longitude at the instrument location"
        units: "degree_E"
        valid_range: [-180.f, 180.f]

    altitude:
      data: 4000.0
      type: float
      attrs:
        long_name: "altitude"
        standard_name: "altitude"
        comment: "Recorded altitude at the instrument location"
        units: m

#-----------------------------------------------------------------
quality_management:
  #---------------------------------------------------------------
  manage_missing_coordinates:
    checker:
      classname: tsdat.qc.checkers.CheckMissing
    handlers:
      - classname: tsdat.qc.handlers.FailPipeline
    variables:
      - COORDS

  manage_coordinate_monotonicity:
    checker:
      classname: tsdat.qc.checkers.CheckMonotonic
    handlers:
      - classname: tsdat.qc.handlers.SortDatasetByCoordinate
        parameters:
          ascending: True
          correction: "Coordinate data was sorted in order to ensure monotonicity."
    variables:
      - COORDS

  #---------------------------------------------------------------
  manage_missing_values:
    checker:
      classname: tsdat.qc.checkers.CheckMissing
    handlers:
      - classname: tsdat.qc.handlers.RemoveFailedValues
      - classname: tsdat.qc.handlers.RecordQualityResults
        parameters:
          bit: 1
          assessment: Bad
          meaning: "Value is equal to _FillValue or NaN"
    variables:
      - DATA_VARS
    exclude: [latitude, longitude, altitude]

  # manage_custom_qc: # Rename this
  #   checker:
  #     classname: ingest.wind_cube_profile.pipeline.qc.CustomQualityChecker
  #   handlers:
  #     - classname: ingest.wind_cube_profile.pipeline.qc.CustomQualityHandler
